// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_tool.sql

package db

import (
	"context"
)

const addAiToolTokenLimit = `-- name: AddAiToolTokenLimit :one
UPDATE ai_tools
SET token_limit = token_limit + $1
WHERE id = $2
RETURNING id, user_id, tool, token_limit, tokens_used, created_at
`

type AddAiToolTokenLimitParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddAiToolTokenLimit(ctx context.Context, arg AddAiToolTokenLimitParams) (AiTool, error) {
	row := q.db.QueryRowContext(ctx, addAiToolTokenLimit, arg.Amount, arg.ID)
	var i AiTool
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const createAiTool = `-- name: CreateAiTool :one
INSERT INTO ai_tools (
    user_id,
    tool,
    token_limit
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, tool, token_limit, tokens_used, created_at
`

type CreateAiToolParams struct {
	UserID     int64  `json:"user_id"`
	Tool       string `json:"tool"`
	TokenLimit int64  `json:"token_limit"`
}

func (q *Queries) CreateAiTool(ctx context.Context, arg CreateAiToolParams) (AiTool, error) {
	row := q.db.QueryRowContext(ctx, createAiTool, arg.UserID, arg.Tool, arg.TokenLimit)
	var i AiTool
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAiTool = `-- name: DeleteAiTool :exec
DELETE FROM ai_tools
WHERE id = $1
`

func (q *Queries) DeleteAiTool(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAiTool, id)
	return err
}

const getAiTool = `-- name: GetAiTool :one
SELECT id, user_id, tool, token_limit, tokens_used, created_at FROM ai_tools
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAiTool(ctx context.Context, id int64) (AiTool, error) {
	row := q.db.QueryRowContext(ctx, getAiTool, id)
	var i AiTool
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getAiToolForUpdate = `-- name: GetAiToolForUpdate :one
SELECT id, user_id, tool, token_limit, tokens_used, created_at FROM ai_tools
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetAiToolForUpdate(ctx context.Context, id int64) (AiTool, error) {
	row := q.db.QueryRowContext(ctx, getAiToolForUpdate, id)
	var i AiTool
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const listAiTools = `-- name: ListAiTools :many
SELECT id, user_id, tool, token_limit, tokens_used, created_at FROM ai_tools
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListAiToolsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAiTools(ctx context.Context, arg ListAiToolsParams) ([]AiTool, error) {
	rows, err := q.db.QueryContext(ctx, listAiTools, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiTool{}
	for rows.Next() {
		var i AiTool
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tool,
			&i.TokenLimit,
			&i.TokensUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAiToolTokenLimit = `-- name: UpdateAiToolTokenLimit :one
UPDATE ai_tools
SET token_limit = $1
WHERE id = $2
RETURNING id, user_id, tool, token_limit, tokens_used, created_at
`

type UpdateAiToolTokenLimitParams struct {
	TokenLimit int64 `json:"token_limit"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateAiToolTokenLimit(ctx context.Context, arg UpdateAiToolTokenLimitParams) (AiTool, error) {
	row := q.db.QueryRowContext(ctx, updateAiToolTokenLimit, arg.TokenLimit, arg.ID)
	var i AiTool
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}
