// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type TokenTransfer struct {
	ID              int64 `json:"id"`
	FromWorkspaceID int64 `json:"from_workspace_id"`
	ToWorkspaceID   int64 `json:"to_workspace_id"`
	// Unused tokens moved to a colleague
	Tokens    int64     `json:"tokens"`
	CreatedAt time.Time `json:"created_at"`
}

type UsageEvent struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
	// can only be negative (spent)
	Tokens    int64     `json:"tokens"`
	CreatedAt time.Time `json:"created_at"`
}

type Workspace struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	TokenLimit int64     `json:"token_limit"`
	TokensUsed int64     `json:"tokens_used"`
	CreatedAt  time.Time `json:"created_at"`
}
