// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token_transfer.sql

package db

import (
	"context"
)

const createTokenTransfer = `-- name: CreateTokenTransfer :one
INSERT INTO token_transfers (
    from_workspace_id,
    to_workspace_id,
    tokens
) VALUES (
    $1, $2, $3
)
RETURNING id, from_workspace_id, to_workspace_id, tokens, created_at
`

type CreateTokenTransferParams struct {
	FromWorkspaceID int64 `json:"from_workspace_id"`
	ToWorkspaceID   int64 `json:"to_workspace_id"`
	Tokens          int64 `json:"tokens"`
}

func (q *Queries) CreateTokenTransfer(ctx context.Context, arg CreateTokenTransferParams) (TokenTransfer, error) {
	row := q.db.QueryRowContext(ctx, createTokenTransfer, arg.FromWorkspaceID, arg.ToWorkspaceID, arg.Tokens)
	var i TokenTransfer
	err := row.Scan(
		&i.ID,
		&i.FromWorkspaceID,
		&i.ToWorkspaceID,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTokenTransfer = `-- name: DeleteTokenTransfer :exec
DELETE FROM token_transfers
WHERE id = $1
`

func (q *Queries) DeleteTokenTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTokenTransfer, id)
	return err
}

const getTokenTransfer = `-- name: GetTokenTransfer :one
SELECT id, from_workspace_id, to_workspace_id, tokens, created_at FROM token_transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTokenTransfer(ctx context.Context, id int64) (TokenTransfer, error) {
	row := q.db.QueryRowContext(ctx, getTokenTransfer, id)
	var i TokenTransfer
	err := row.Scan(
		&i.ID,
		&i.FromWorkspaceID,
		&i.ToWorkspaceID,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const listTokenTransfers = `-- name: ListTokenTransfers :many
SELECT id, from_workspace_id, to_workspace_id, tokens, created_at FROM token_transfers
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListTokenTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTokenTransfers(ctx context.Context, arg ListTokenTransfersParams) ([]TokenTransfer, error) {
	rows, err := q.db.QueryContext(ctx, listTokenTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TokenTransfer{}
	for rows.Next() {
		var i TokenTransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromWorkspaceID,
			&i.ToWorkspaceID,
			&i.Tokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenTransferTokens = `-- name: UpdateTokenTransferTokens :one
UPDATE token_transfers
SET tokens = $1
WHERE id = $2
RETURNING id, from_workspace_id, to_workspace_id, tokens, created_at
`

type UpdateTokenTransferTokensParams struct {
	Tokens int64 `json:"tokens"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateTokenTransferTokens(ctx context.Context, arg UpdateTokenTransferTokensParams) (TokenTransfer, error) {
	row := q.db.QueryRowContext(ctx, updateTokenTransferTokens, arg.Tokens, arg.ID)
	var i TokenTransfer
	err := row.Scan(
		&i.ID,
		&i.FromWorkspaceID,
		&i.ToWorkspaceID,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}
