// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_event.sql

package db

import (
	"context"
)

const createUsageEvent = `-- name: CreateUsageEvent :one
INSERT INTO usage_events (
    workspace_id,
    tokens
) VALUES (
    $1, $2
)
RETURNING id, workspace_id, tokens, created_at
`

type CreateUsageEventParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Tokens      int64 `json:"tokens"`
}

func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRowContext(ctx, createUsageEvent, arg.WorkspaceID, arg.Tokens)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUsageEvent = `-- name: DeleteUsageEvent :exec
DELETE FROM usage_events
WHERE id = $1
`

func (q *Queries) DeleteUsageEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUsageEvent, id)
	return err
}

const getUsageEvent = `-- name: GetUsageEvent :one
SELECT id, workspace_id, tokens, created_at FROM usage_events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUsageEvent(ctx context.Context, id int64) (UsageEvent, error) {
	row := q.db.QueryRowContext(ctx, getUsageEvent, id)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageEvents = `-- name: ListUsageEvents :many
SELECT id, workspace_id, tokens, created_at FROM usage_events
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsageEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsageEvents(ctx context.Context, arg ListUsageEventsParams) ([]UsageEvent, error) {
	rows, err := q.db.QueryContext(ctx, listUsageEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageEvent{}
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Tokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsageEventTokens = `-- name: UpdateUsageEventTokens :one
UPDATE usage_events
SET tokens = $1
WHERE id = $2
RETURNING id, workspace_id, tokens, created_at
`

type UpdateUsageEventTokensParams struct {
	Tokens int64 `json:"tokens"`
	ID     int64 `json:"id"`
}

func (q *Queries) UpdateUsageEventTokens(ctx context.Context, arg UpdateUsageEventTokensParams) (UsageEvent, error) {
	row := q.db.QueryRowContext(ctx, updateUsageEventTokens, arg.Tokens, arg.ID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}
