// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"
)

const addWorkspaceTokenLimit = `-- name: AddWorkspaceTokenLimit :one
UPDATE workspaces
SET token_limit = token_limit + $1
WHERE id = $2
RETURNING id, name, token_limit, tokens_used, created_at
`

type AddWorkspaceTokenLimitParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddWorkspaceTokenLimit(ctx context.Context, arg AddWorkspaceTokenLimitParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, addWorkspaceTokenLimit, arg.Amount, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    name,
    token_limit
) VALUES (
    $1, $2
)
RETURNING id, name, token_limit, tokens_used, created_at
`

type CreateWorkspaceParams struct {
	Name       string `json:"name"`
	TokenLimit int64  `json:"token_limit"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Name, arg.TokenLimit)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, token_limit, tokens_used, created_at FROM workspaces
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceForUpdate = `-- name: GetWorkspaceForUpdate :one
SELECT id, name, token_limit, tokens_used, created_at FROM workspaces
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetWorkspaceForUpdate(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceForUpdate, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, token_limit, tokens_used, created_at FROM workspaces
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListWorkspacesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenLimit,
			&i.TokensUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceTokenLimit = `-- name: UpdateWorkspaceTokenLimit :one
UPDATE workspaces
SET token_limit = $1
WHERE id = $2
RETURNING id, name, token_limit, tokens_used, created_at
`

type UpdateWorkspaceTokenLimitParams struct {
	TokenLimit int64 `json:"token_limit"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateWorkspaceTokenLimit(ctx context.Context, arg UpdateWorkspaceTokenLimitParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspaceTokenLimit, arg.TokenLimit, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenLimit,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}
